image: alpine/latest

packages:
  - curl

sources:
  - https://git.sr.ht/~rcr/rirc

tasks:
  - build: |
      cd rirc
      make
  - check: |
      cd rirc
      make -f Makefile.dev check

triggers:
  - action: email
    condition: failure
    to: mail+sourcehut+builds@rcr.io
