image: openbsd/latest

packages:
  - curl
  - gmake

sources:
  - https://git.sr.ht/~rcr/rirc

tasks:
  - build: |
      cd rirc
      gmake
  - check: |
      cd rirc
      gmake -f Makefile.dev clean-lib clean-dev
      gmake -f Makefile.dev rirc.debug check

triggers:
  - action: email
    condition: failure
    to: mail+sourcehut+builds@rcr.io
